public class Sobremesa extends Refeicao{
    @Override
    public void preparar() {
        System.out.println("OS MACACOS INVADIRAM A COZINHA CORRE MZR SENAO VAO MATAR A GENTE");
    }

    @Override
    public void servir() {
        System.out.println("UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA UGA");
    }
}
